config/routes.rb
Rails.application.routes.draw do
  resources :parking_spots, only: :index
  resources :vehicles, only: :index do
    put :toggle_parking
  end
  resources :parkings, only: :index
  root 'parking_spots#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < Vehicle
end

app/models/car.rb
class Car < Vehicle
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :vehicle
  belongs_to :parking_spot

  # Scopes
  scope :active, -> { where(end_time: nil) }

  def complete!
    update(end_time: Time.current)
  end
end

app/models/parking_spot.rb
class ParkingSpot < ApplicationRecord
  has_many :parkings, dependent: :destroy

  validates :spot_type, inclusion: { in: %w(car bike),
    message: "%{value} is not a valid stop type" }

  # Scopes
  scope :available, -> { where(occupied: false) }

  def free!
    update(occupied: false)
  end

  def occupy!
    update(occupied: true)
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :parkings, dependent: :destroy
  has_many :parking_spots, through: :parkings

  # Scopes
  scope :search, ->(text) { where("lower(registration_number) like '%#{text.downcase}%' OR lower(type) like '%#{text.downcase}%'") }

  def toggle_status
    parked ? unpark : park
    toggle!(:parked)
  end

  def unpark
    parking = parkings.active.first
    parking.parking_spot.free!
    parking.complete!
  end

  def park
    spot = ParkingSpot.available.first
    parkings.create(parking_spot_id: spot.id, start_time: Time.current)
    spot.occupy!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/parking_spots_controller.rb
# frozen_string_literal: true

class ParkingSpotsController < ApplicationController
  def index
    @parking_spots = ParkingSpot.order(:id).paginate(page: params[:page])
  end
end

app/controllers/parkings_controller.rb
# frozen_string_literal: true

class ParkingsController < ApplicationController
  def index
    @parkings = Parking.order(:id).paginate(page: params[:page]).includes(:vehicle, :parking_spot)
  end
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :find_vehicle, only: :toggle_parking

  def index
    @vehicles = if params[:search].present?
                  Vehicle.search(params[:search])
                else
                  Vehicle
                end.order(:id).paginate(page: params[:page])
  end

  def toggle_parking
    if @vehicle.toggle_status
      message = "Vehicle #{@vehicle.parked? ? 'parked' : 'unparked'}!"
      redirect_to_with(message, :notice)
    else
      redirect_to_with(error_message(@vehicle), :error)
    end
  end

  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  rescue
    redirect_to_with('Vehicle not found.', :error)
  end

  def redirect_to_with(message, type)
    flash[type] = message
    redirect_to vehicles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_class(links)
    navigation_class = ''
    links.each do |link|
      recognized = Rails.application.routes.recognize_path(link)
      if recognized[:controller] == params[:controller] && recognized[:action] == params[:action]
        navigation_class += ' active'
      else
        navigation_class += ''
      end
    end
    navigation_class
  end

  def page_title
    @page_title || 'Parking Lot'
  end

  def page_description
    @page_description || 'This is a solution to solve the parking problems.'
  end

  def page_keywords
    @page_keywords || 'Parking Lot, Parking Lot Website, Parking Spots'
  end
end

app/helpers/flash_helper.rb
# frozen_string_literal: true

module FlashHelper
  ALERT_TYPES = %i[danger info success warning].freeze unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      type = get_flash_type(type)
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        flash_messages << get_message_text(type, message) if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def get_flash_type(type)
    type = type.to_sym
    type = :success if type == :notice
    type = :danger if type == :alert
    type
  end

  def get_message_text(type, message)
    content_tag(:div, message.html_safe, class: "alert bg-#{type} alert-#{type} text-white")
  end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark.mb-5
  = link_to 'Parking Lot', root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        = link_to 'Parking Spots', parking_spots_path, class: "nav-item nav-link#{nav_class([parking_spots_path])}"
      %li.nav-item
        = link_to 'Vehicles', vehicles_path, class: "nav-item nav-link#{nav_class([vehicles_path])}"
      %li.nav-item
        = link_to 'Parking History', parkings_path, class: "nav-item nav-link#{nav_class([parkings_path])}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => page_keywords, :name => "keywords"}
    %meta{:content => page_description, :name => "description"}
    %meta{:charset => "UTF-8"}
    %title= page_title
    = csrf_meta_tags
    = csp_meta_tag
    %script{:src => "//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"}
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .content.mt-60
      = bootstrap_flash
      = yield

app/views/parking_spots/index.html.haml
.container
  .row
    .col-sm-6
      %h2 Parking Spots
    .col-sm-6
      = link_to 'New Parking Spot', '#', class: "float-right btn btn-success"
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Name
        %th Spot Type
        %th Available
    %tbody
      - if @parking_spots.present?
        - @parking_spots.each do |spot|
          %tr
            %td= spot.name
            %td= spot.spot_type.humanize
            %td= !spot.occupied ? 'Yes' : 'No'
  - if @parking_spots.present?
    .col-sm-12.reports-Header
      #discount-definition-paginator.mb-0
        = will_paginate @parking_spots
  - else
    No records found

app/views/parkings/index.html.haml
.container
  .row
    %h2 Parking History
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Vehicle Type
        %th Registration Number
        %th Parking Spot
        %th Parked at
        %th Left at
    %tbody
      - if @parkings.present?
        - @parkings.each do |parking|
          %tr
            %td= parking.vehicle.type
            %td= parking.vehicle.registration_number
            %td= parking.parking_spot.name
            %td= parking.start_time
            %td= parking.end_time
  - if @parkings.present?
    .col-sm-12.reports-Header
      #discount-definition-paginator.mb-0
        = will_paginate @parkings
  - else
    No records found

app/views/vehicles/index.html.haml
.container
  .row
    .col-sm-6
      %h2 Vehicles
    .col-sm-6
      = form_tag('', method: 'get', class: 'form-inline my-2 pull-right width-100p') do
        = text_field_tag :search, params[:search], placeholder: 'Search with registration number and vehile type', class: 'form-control width-85p'
        = submit_tag 'Search', :class => 'btn btn-outline-success my-2 my-sm-0 width-15p'

  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Vehicle Type
        %th Registration Number
        %th Is Parked
        %th Action
    %tbody
      - if @vehicles.present?
        - @vehicles.each do |vehicle|
          %tr
            %td= vehicle.type
            %td= vehicle.registration_number
            %td= vehicle.parked ? 'Yes' : 'No'
            %td= link_to (vehicle.parked? ? 'Unpark' : 'Park'), vehicle_toggle_parking_path(vehicle), method: :put
  - if @vehicles.present?
    .col-sm-12.reports-Header
      #discount-definition-paginator.mb-0
        = will_paginate @vehicles
  - else
    No records found